---
db_filepath: "./sys/media.db"

server:
    port: 8080
    shutdown_timeout: 5

service:
    channel_size: 10000
    workers: 2
    attempts: 2
    output_dir: "/opt/media-service"

storage_manager:
    log_channel_size: 1000
    file_channel_size: 100

cache_manager:
    size: 20
    expiration: 300
